#!/usr/bin/env python3
"""Record every host the browser contacts on its own, with no user action.

  python3 utils/audit_network.py
  python3 utils/audit_network.py --seconds 40 --url https://example.com

Launches a build against a throwaway profile with network logging enabled,
sits idle, then reports which hosts were contacted and how often. Anything
listed here is traffic the browser generated by itself, so it is the list
worth arguing about. Re-run after a privacy patch to prove a host is gone.

Exit code is 1 if any host outside --allow was contacted, so this can gate a
release once the expected set is settled.
"""

import argparse
import json
import re
import shutil
import subprocess
import sys
import tempfile
import time
from collections import Counter
from pathlib import Path
from urllib.parse import urlparse

import config

DEFAULT_BINARY = config.CHROMIUM_SRC / "out" / "baseline" / "chrome.exe"

LOCAL_SCHEMES = {"about", "chrome", "chrome-extension", "chrome-untrusted",
                 "data", "blob", "file", "javascript", "devtools"}

URL_PATTERN = re.compile(r'"url":\s*"([^"]{1,2048})"')


def capture(binary: Path, seconds: int, url: str) -> str:
    """Run the browser briefly and return the raw netlog text."""
    profile = Path(tempfile.mkdtemp(prefix="shiemi-audit-"))
    netlog = profile / "netlog.json"

    proc = subprocess.Popen([
        str(binary),
        f"--user-data-dir={profile}",
        f"--log-net-log={netlog}",
        "--net-log-capture-mode=Everything",
        "--no-first-run",
        "--no-default-browser-check",
        url,
    ])

    try:
        time.sleep(seconds)
    finally:
        proc.terminate()
        try:
            proc.wait(timeout=30)
        except subprocess.TimeoutExpired:
            proc.kill()
            proc.wait(timeout=30)

    # The netlog is written incrementally, so a truncated tail is normal and
    # the text is scraped rather than parsed as JSON.
    time.sleep(2)
    text = netlog.read_text(encoding="utf-8", errors="replace") if netlog.exists() else ""
    shutil.rmtree(profile, ignore_errors=True)
    return text


def external_urls(text: str) -> list:
    """Parsed URLs from the log, excluding anything that stays on the machine."""
    found = []
    for raw in URL_PATTERN.findall(text):
        parsed = urlparse(raw)
        if parsed.scheme in LOCAL_SCHEMES or not parsed.hostname:
            continue
        found.append(parsed)
    return found


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--binary", type=Path, default=DEFAULT_BINARY)
    parser.add_argument("--seconds", type=int, default=30)
    parser.add_argument("--url", default="about:blank",
                        help="page to open; defaults to a blank tab so the "
                             "only traffic is the browser's own")
    parser.add_argument("--allow", nargs="*", default=[],
                        help="hosts that are expected and should not fail")
    parser.add_argument("--urls", action="store_true",
                        help="also list the endpoint paths per host")
    args = parser.parse_args()

    if not args.binary.exists():
        raise SystemExit(f"no browser at {args.binary} - build it first")

    print(f"recording {args.seconds}s from {args.binary}")
    print(f"opening {args.url}\n")

    text = capture(args.binary, args.seconds, args.url)
    if not text:
        raise SystemExit("no netlog was written")

    parsed_urls = external_urls(text)
    counts = Counter(p.hostname for p in parsed_urls)
    if not counts:
        print("no external hosts contacted")
        return 0

    def is_allowed(host: str) -> bool:
        return any(host == a or host.endswith(f".{a}") for a in args.allow)

    width = max(len(host) for host in counts)
    unexpected = []
    for host, count in counts.most_common():
        allowed = is_allowed(host)
        if not allowed:
            unexpected.append(host)
        mark = "    " if allowed else "  ! "
        print(f"{mark}{host.ljust(width)}  {count}")

        if args.urls:
            # Queries carry ids and are noisy; the path identifies the service.
            endpoints = Counter(
                f"{p.scheme}://{p.hostname}{p.path}"
                for p in parsed_urls
                if p.hostname == host
            )
            for endpoint, n in endpoints.most_common():
                print(f"        {n:>3}  {endpoint}")

    print(f"\n{len(counts)} hosts, {sum(counts.values())} requests")
    if args.allow and unexpected:
        print(f"{len(unexpected)} not in --allow")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
