#!/usr/bin/env python3
"""Record every host the browser contacts on its own, with no user action.

  python3 utils/audit_network.py
  python3 utils/audit_network.py --seconds 40 --url https://example.com
  python3 utils/audit_network.py --urls

Launches a build against a throwaway profile with network logging enabled,
sits idle, then reports which hosts were contacted and how often. Anything
listed here is traffic the browser generated by itself, so it is the list
worth arguing about. Re-run after a privacy patch to prove a host is gone.

Each request is attributed to the Chromium subsystem that made it, resolved
from the traffic annotation in the log, so the output names the file to patch
instead of leaving a hostname to guess at.

Exit code is 1 if any host outside --allow was contacted, so this can gate a
release once the expected set is settled.
"""

import argparse
import re
import shutil
import subprocess
import sys
import tempfile
import time
from collections import Counter, defaultdict
from pathlib import Path
from urllib.parse import urlparse

import config

DEFAULT_BINARY = config.CHROMIUM_SRC / "out" / "baseline" / "chrome.exe"
ANNOTATIONS = (config.CHROMIUM_SRC / "tools" / "traffic_annotation" / "summary"
               / "annotations.xml")

LOCAL_SCHEMES = {"about", "chrome", "chrome-extension", "chrome-untrusted",
                 "data", "blob", "file", "javascript", "devtools"}

URL_PATTERN = re.compile(r'"url":\s*"([^"]{1,2048})"')
ANNOTATION_PATTERN = re.compile(r'"traffic_annotation":\s*(-?\d+)')
ITEM_PATTERN = re.compile(r'<item id="([^"]+)"[^>]*?file_path="([^"]*)"')

UNANNOTATED = "(unannotated)"


def annotation_hash(name: str) -> int:
    """Chromium's consteval hash over an annotation's unique id."""
    value = 0
    for byte in name.encode():
        value = (value * 31 + byte) % 138003713
    return value


def load_annotations() -> dict:
    if not ANNOTATIONS.exists():
        return {}
    text = ANNOTATIONS.read_text(encoding="utf-8", errors="replace")
    return {annotation_hash(name): (name, path)
            for name, path in ITEM_PATTERN.findall(text)}


def capture(binary: Path, seconds: int, url: str) -> Path:
    """Run the browser briefly and return the netlog path."""
    profile = Path(tempfile.mkdtemp(prefix="shiemi-audit-"))
    netlog = profile / "netlog.json"

    proc = subprocess.Popen([
        str(binary),
        f"--user-data-dir={profile}",
        f"--log-net-log={netlog}",
        "--net-log-capture-mode=Everything",
        "--no-first-run",
        "--no-default-browser-check",
        url,
    ])

    try:
        time.sleep(seconds)
    finally:
        proc.terminate()
        try:
            proc.wait(timeout=30)
        except subprocess.TimeoutExpired:
            proc.kill()
            proc.wait(timeout=30)

    time.sleep(2)
    return netlog


def requests_from(netlog: Path):
    """Every external request in the log, as (parsed url, annotation hash).

    The log is streamed a line at a time because capture-mode Everything runs
    to hundreds of megabytes. One event per line means a url and the annotation
    on the same line belong to the same request. A truncated tail is normal
    after terminating the browser, so lines are scraped rather than parsed.
    """
    for line in netlog.open(encoding="utf-8", errors="replace"):
        found = URL_PATTERN.search(line)
        if not found:
            continue
        parsed = urlparse(found.group(1))
        if parsed.scheme in LOCAL_SCHEMES or not parsed.hostname:
            continue
        tag = ANNOTATION_PATTERN.search(line)
        yield parsed, int(tag.group(1)) if tag else None


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--binary", type=Path, default=DEFAULT_BINARY)
    parser.add_argument("--seconds", type=int, default=30)
    parser.add_argument("--url", default="about:blank",
                        help="page to open; defaults to a blank tab so the "
                             "only traffic is the browser's own")
    parser.add_argument("--allow", nargs="*", default=[],
                        help="hosts that are expected and should not fail")
    parser.add_argument("--urls", action="store_true",
                        help="also list the endpoint paths per host")
    args = parser.parse_args()

    if not args.binary.exists():
        raise SystemExit(f"no browser at {args.binary} - build it first")

    print(f"recording {args.seconds}s from {args.binary}")
    print(f"opening {args.url}\n")

    annotations = load_annotations()
    if not annotations:
        print(f"warning: no annotations at {ANNOTATIONS}, "
              "requests will not be attributed\n", file=sys.stderr)

    netlog = capture(args.binary, args.seconds, args.url)
    if not netlog.exists():
        raise SystemExit("no netlog was written")

    counts = Counter()
    blamed = defaultdict(Counter)
    endpoints = defaultdict(Counter)
    try:
        for parsed, tag in requests_from(netlog):
            host = parsed.hostname
            counts[host] += 1
            name, path = annotations.get(tag, (UNANNOTATED, ""))
            blamed[host][(name, path)] += 1
            if args.urls:
                endpoints[host][f"{parsed.scheme}://{host}{parsed.path}"] += 1
    finally:
        shutil.rmtree(netlog.parent, ignore_errors=True)

    if not counts:
        print("no external hosts contacted")
        return 0

    def is_allowed(host: str) -> bool:
        return any(host == a or host.endswith(f".{a}") for a in args.allow)

    width = max(len(host) for host in counts)
    unexpected = []
    for host, count in counts.most_common():
        allowed = is_allowed(host)
        if not allowed:
            unexpected.append(host)
        mark = "    " if allowed else "  ! "
        print(f"{mark}{host.ljust(width)}  {count}")

        for (name, path), n in blamed[host].most_common():
            print(f"        {n:>3}  {name}")
            if path:
                print(f"             {path}")

        if args.urls:
            for endpoint, n in endpoints[host].most_common():
                print(f"        {n:>3}  {endpoint}")

    print(f"\n{len(counts)} hosts, {sum(counts.values())} requests")
    if args.allow and unexpected:
        print(f"{len(unexpected)} not in --allow")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
