#!/usr/bin/env python3
"""Record every host the browser contacts on its own, with no user action.

  python3 utils/audit_network.py
  python3 utils/audit_network.py --seconds 40 --url https://example.com
  python3 utils/audit_network.py --urls
  python3 utils/audit_network.py --flag --enable-features=SomeFeature

Launches a build against a throwaway profile with network logging enabled,
sits idle, then reports which hosts were contacted and how often. Anything
listed here is traffic the browser generated by itself, so it is the list
worth arguing about. Re-run after a privacy patch to prove a host is gone.

Each request is attributed to the Chromium subsystem that made it, resolved
from the traffic annotation in the log, so the output names the file to patch
instead of leaving a hostname to guess at.

Which hosts appear is stable between runs. How many requests each one made is
not: component update checks vary from one to six per run regardless of window
length, so treat a changed request count as noise and a host appearing or
disappearing as the real signal.

--headless reports the same hosts and counts as a windowed run, so prefer it:
nothing takes focus while the audit is running.

Exit code is 1 if any host outside the allowed set was contacted, so this can
gate a release. Prefer --baseline over --allow for that: the expected hosts
then live in a reviewed file, and adding one shows up in a diff with the
reason next to it.
"""

import argparse
import re
import shutil
import subprocess
import sys
import tempfile
import time
from collections import Counter, defaultdict
from pathlib import Path
from urllib.parse import urlparse

import config

DEFAULT_BINARY = config.CHROMIUM_SRC / "out" / "baseline" / "chrome.exe"
DEFAULT_BASELINE = config.ROOT / "tests" / "network-allowed.txt"
ANNOTATIONS = (config.CHROMIUM_SRC / "tools" / "traffic_annotation" / "summary"
               / "annotations.xml")

LOCAL_SCHEMES = {"about", "chrome", "chrome-extension", "chrome-untrusted",
                 "data", "blob", "file", "javascript", "devtools"}

URL_PATTERN = re.compile(r'"url":\s*"([^"]{1,2048})"')
ANNOTATION_PATTERN = re.compile(r'"traffic_annotation":\s*(-?\d+)')
SOURCE_PATTERN = re.compile(r'"source":\s*\{"id":\s*(\d+)[^}]*"type":\s*(\d+)\}')
URL_REQUEST_SOURCE = 1
ITEM_PATTERN = re.compile(r'<item id="([^"]+)"[^>]*?file_path="([^"]*)"')

UNANNOTATED = "(unannotated)"


def read_baseline(path: Path) -> list:
    if not path.exists():
        raise SystemExit(f"no baseline at {path}")
    hosts = []
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.split("#", 1)[0].strip()
        if line:
            hosts.append(line)
    return hosts


def allows(host: str, allowed) -> bool:
    """Whether host is covered by the allowed list, subdomains included."""
    return any(host == entry or host.endswith(f".{entry}") for entry in allowed)


def annotation_hash(name: str) -> int:
    """Chromium's consteval hash over an annotation's unique id."""
    value = 0
    for byte in name.encode():
        value = (value * 31 + byte) % 138003713
    return value


def load_annotations() -> dict:
    if not ANNOTATIONS.exists():
        return {}
    text = ANNOTATIONS.read_text(encoding="utf-8", errors="replace")
    return {annotation_hash(name): (name, path)
            for name, path in ITEM_PATTERN.findall(text)}


def capture(binary: Path, seconds: int, url: str, flags: list) -> Path:
    """Run the browser briefly and return the netlog path."""
    profile = Path(tempfile.mkdtemp(prefix="shiemi-audit-"))
    netlog = profile / "netlog.json"

    proc = subprocess.Popen([
        str(binary),
        f"--user-data-dir={profile}",
        f"--log-net-log={netlog}",
        "--net-log-capture-mode=Everything",
        "--no-first-run",
        "--no-default-browser-check",
        *flags,
        url,
    ])

    try:
        time.sleep(seconds)
    finally:
        proc.terminate()
        try:
            proc.wait(timeout=30)
        except subprocess.TimeoutExpired:
            proc.kill()
            proc.wait(timeout=30)

    time.sleep(2)
    return netlog


def requests_from(netlog: Path) -> dict:
    """External requests in the log, keyed by netlog source id.

    One request spans many events across several sources, so counting events
    or sockets overstates it. Only URL_REQUEST sources are counted, grouped by
    id, which lets the annotation be picked up from whichever event carried it.

    The log is streamed a line at a time because capture-mode Everything runs
    to hundreds of megabytes. A truncated tail is normal after terminating the
    browser, so lines are scraped rather than parsed.
    """
    found = {}
    for line in netlog.open(encoding="utf-8", errors="replace"):
        url = URL_PATTERN.search(line)
        source = SOURCE_PATTERN.search(line)
        if not url or not source:
            continue
        if int(source.group(2)) != URL_REQUEST_SOURCE:
            continue
        parsed = urlparse(url.group(1))
        if parsed.scheme in LOCAL_SCHEMES or not parsed.hostname:
            continue
        key = int(source.group(1))
        tag = ANNOTATION_PATTERN.search(line)
        tag = int(tag.group(1)) if tag else None
        if key in found:
            if tag is not None and found[key][1] is None:
                found[key] = (found[key][0], tag)
        else:
            found[key] = (parsed, tag)
    return found


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--binary", type=Path, default=DEFAULT_BINARY)
    parser.add_argument("--seconds", type=int, default=30)
    parser.add_argument("--url", default="about:blank",
                        help="page to open; defaults to a blank tab so the "
                             "only traffic is the browser's own")
    parser.add_argument("--allow", action="extend", nargs="*", default=[],
                        help="hosts that are expected and should not fail; "
                             "repeatable, and accepts several per flag")
    parser.add_argument("--baseline", nargs="?", type=Path,
                        const=DEFAULT_BASELINE, metavar="FILE",
                        help=f"read the allowed hosts from a file instead, "
                             f"one per line with # comments "
                             f"(default: {DEFAULT_BASELINE.name})")
    parser.add_argument("--urls", action="store_true",
                        help="also list the endpoint paths per host")
    parser.add_argument("--flag", action="append", default=[], metavar="ARG",
                        help="extra browser switch, repeatable; use to try a "
                             "feature before committing to a patch")
    parser.add_argument("--headless", action="store_true",
                        help="run without opening a window")
    args = parser.parse_args()

    flags = args.flag + (["--headless"] if args.headless else [])

    allowed = list(args.allow)
    if args.baseline:
        allowed += read_baseline(args.baseline)

    if not args.binary.exists():
        raise SystemExit(f"no browser at {args.binary} - build it first")

    print(f"recording {args.seconds}s from {args.binary}")
    print(f"opening {args.url}\n")

    annotations = load_annotations()
    if not annotations:
        print(f"warning: no annotations at {ANNOTATIONS}, "
              "requests will not be attributed\n", file=sys.stderr)

    netlog = capture(args.binary, args.seconds, args.url, flags)
    if not netlog.exists():
        raise SystemExit("no netlog was written")

    counts = Counter()
    blamed = defaultdict(Counter)
    endpoints = defaultdict(Counter)
    try:
        for parsed, tag in requests_from(netlog).values():
            host = parsed.hostname
            counts[host] += 1
            name, path = annotations.get(tag, (UNANNOTATED, ""))
            blamed[host][(name, path)] += 1
            if args.urls:
                endpoints[host][f"{parsed.scheme}://{host}{parsed.path}"] += 1
    finally:
        shutil.rmtree(netlog.parent, ignore_errors=True)

    if not counts:
        print("no external hosts contacted")
        return 0

    width = max(len(host) for host in counts)
    unexpected = []
    for host, count in counts.most_common():
        permitted = allows(host, allowed)
        if not permitted:
            unexpected.append(host)
        mark = "    " if permitted else "  ! "
        print(f"{mark}{host.ljust(width)}  {count}")

        for (name, path), n in blamed[host].most_common():
            print(f"        {n:>3}  {name}")
            if path:
                print(f"             {path}")

        if args.urls:
            for endpoint, n in endpoints[host].most_common():
                print(f"        {n:>3}  {endpoint}")

    print(f"\n{len(counts)} hosts, {sum(counts.values())} requests")
    if unexpected:
        source = args.baseline if args.baseline else "--allow"
        print(f"{len(unexpected)} not in {source}")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
