#!/usr/bin/env python3
"""Configure and build Shiemi from the Chromium checkout.

  python3 utils/build.py                       # baseline flags, target chrome
  python3 utils/build.py --flags release
  python3 utils/build.py --gen-only
  python3 utils/build.py --jobs 16 --no-yield  # take the whole machine

Requires depot_tools on PATH. Output goes to out/<flags> unless --out says
otherwise, so dev and release builds do not clobber each other.

A release build saturates every core for hours. By default the compiler is
left four cores and runs below normal priority, so the machine stays usable
while it works. Pass --no-yield when nobody is at the keyboard.
"""

import argparse
import os
import shutil
import subprocess
import sys

import config
import rebrand

# Enough to keep a browser, an editor and a game responsive. Below normal
# priority alone is not enough: it yields on CPU but the compiler still takes
# every core's worth of memory bandwidth.
RESERVED_CORES = 4


def default_jobs() -> int:
    return max(1, (os.cpu_count() or 8) - RESERVED_CORES)


def run(cmd: str, cwd, yield_cpu: bool = False) -> int:
    # gn and autoninja are .bat wrappers, so this goes through the shell.
    print("+ " + cmd)
    flags = 0
    if yield_cpu and sys.platform == "win32":
        # Children inherit it, so the whole compiler fan-out drops with it.
        flags = subprocess.BELOW_NORMAL_PRIORITY_CLASS
    return subprocess.run(cmd, cwd=str(cwd), shell=True,
                          creationflags=flags).returncode


def overlay_branding(src) -> int:
    """Copy branding art over the Chromium tree, returning the number written.

    Copied rather than patched: a binary .ico inside a unified diff has to be
    regenerated by hand at every rebase. Unchanged files are left alone, since
    touching a resource costs a relink.
    """
    icons = config.ROOT / "branding" / "icons"
    if not icons.is_dir():
        return 0

    theme = src / "chrome" / "app" / "theme" / "chromium"
    pairs = [(p, theme / p.name) for p in sorted(icons.glob("*.png"))]
    pairs += [(p, theme / "win" / p.name)
              for p in sorted((icons / "win").glob("*.ico"))]

    # The logo WebUI draws is a chrome_scaled_image, which resolves under the
    # density directories rather than the flat theme one, so it needs its own
    # copy or chrome://theme/current-channel-logo keeps serving Chromium's.
    for density in ("default_100_percent", "default_200_percent"):
        pairs += [(p, src / "chrome" / "app" / "theme" / density / "chromium" / p.name)
                  for p in sorted((icons / density).glob("*.png"))]

    # branding/vector mirrors the Chromium tree, so the relative path is the
    # destination. These are the product logo drawn in infobars and dialogs,
    # which comes from .icon sources rather than the theme PNGs.
    vector = config.ROOT / "branding" / "vector"
    pairs += [(p, src / p.relative_to(vector))
              for p in sorted(vector.rglob("*"))
              if p.is_file()]

    written = 0
    for source, dest in pairs:
        if not dest.parent.is_dir():
            continue
        if dest.exists() and dest.read_bytes() == source.read_bytes():
            continue
        shutil.copyfile(source, dest)
        written += 1
    return written


STYLE_OVERLAYS = {
    "cr_shared_vars.css": "ui/webui/resources/cr_elements/cr_shared_vars.css",
    "interstitial_core.css":
        "components/security_interstitials/core/common/resources/"
        "interstitial_core.css",
}

STYLE_BEGIN = "/* shiemi:begin */"
STYLE_END = "/* shiemi:end */"


def append_styles(src) -> int:
    """Append our WebUI tokens to Chromium's, returning the number written.

    Appended rather than patched or overwritten. These token files are long
    and churn upstream, so a diff would conflict every rebase and a straight
    copy would silently drop whatever upstream added. Appending only ever
    reacts to the tail of the file, and cascade order does the rest: the
    block lands last, so it wins ties.
    """
    styles = config.ROOT / "styles"
    if not styles.is_dir():
        return 0

    written = 0
    for name, relative in STYLE_OVERLAYS.items():
        source = styles / name
        dest = src.joinpath(*relative.split("/"))
        if not source.is_file() or not dest.is_file():
            continue

        current = dest.read_text(encoding="utf-8")
        start = current.find(STYLE_BEGIN)
        if start != -1:
            end = current.find(STYLE_END, start)
            if end == -1:
                raise SystemExit(f"unterminated shiemi block in {dest}")
            current = current[:start] + current[end + len(STYLE_END):]

        block = source.read_text(encoding="utf-8")
        content = (f"{current.rstrip()}\n\n{STYLE_BEGIN}\n{block.rstrip()}\n"
                   f"{STYLE_END}\n")
        if content == dest.read_text(encoding="utf-8"):
            continue
        dest.write_text(content, encoding="utf-8", newline="\n")
        written += 1
    return written


def install_defaults(out_dir) -> bool:
    """Put initial_preferences beside the binary, where first run reads it.

    Chromium looks for it in the executable's own directory, so a dev build
    only picks up the shipped defaults if it is copied out here too.
    """
    source = config.ROOT / "defaults" / "initial_preferences"
    if not source.is_file() or not out_dir.is_dir():
        return False
    dest = out_dir / "initial_preferences"
    if dest.exists() and dest.read_bytes() == source.read_bytes():
        return False
    shutil.copyfile(source, dest)
    return True


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--flags", default="baseline", help="name in flags/, without .gn"
    )
    parser.add_argument("--out", help="output dir under out/ (default: same as --flags)")
    parser.add_argument("--target", default="chrome")
    parser.add_argument("--gen-only", action="store_true")
    parser.add_argument("--jobs", type=int, default=default_jobs(),
                        help=f"parallel compiles (default: cores minus "
                             f"{RESERVED_CORES})")
    parser.add_argument("--no-yield", action="store_true",
                        help="run at normal priority and take every core")
    args = parser.parse_args()

    src = config.require_src()
    flags_file = config.FLAGS_DIR / f"{args.flags}.gn"
    if not flags_file.exists():
        raise SystemExit(f"no such flags file: {flags_file}")

    out_name = args.out or args.flags
    out_dir = f"out\\{out_name}"
    out_path = src / "out" / out_name

    print(f"chromium {config.checkout_version()} at {src}")
    print(f"flags    {flags_file.name} -> {out_dir}")

    written = overlay_branding(src)
    if written:
        print(f"branding {written} asset(s) copied into the tree")

    styled = append_styles(src)
    if styled:
        print(f"styles   {styled} webui token file(s) extended")

    renamed = rebrand.apply(src)
    if renamed:
        print(f"strings  {renamed} message(s) rebranded")

    # Not --args: cmd.exe eats the quotes in gn string values.
    out_path.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(flags_file, out_path / "args.gn")

    rc = run(f"gn gen {out_dir}", src)
    if rc != 0:
        return rc
    if args.gen_only:
        return 0

    cores = os.cpu_count() or 0
    if args.no_yield:
        print(f"jobs     all {cores} core(s), normal priority")
        rc = run(f"autoninja -C {out_dir} {args.target}", src)
    else:
        print(f"jobs     {args.jobs} of {cores} core(s), below normal priority")
        rc = run(f"autoninja -C {out_dir} -j {args.jobs} {args.target}", src,
                 yield_cpu=True)

    if rc == 0 and install_defaults(out_path):
        print("defaults initial_preferences copied beside the binary")
    return rc


if __name__ == "__main__":
    sys.exit(main())
